//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWeb2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }

        [Key]
        public int IDCus { get; set; }

        [MaxLength] // Không cần chỉ định độ dài tối đa vì là kiểu nvarchar(max)
        public string NameCus { get; set; }

        [MaxLength(15)]
        public string PhoneCus { get; set; }

        [MaxLength] // Không cần chỉ định độ dài tối đa vì là kiểu nvarchar(max)
        public string EmailCus { get; set; }

        [Required]
        [MaxLength(50)]
        public string PassCus { get; set; }

        [MaxLength] // Không cần chỉ định độ dài tối đa vì là kiểu nvarchar(max)
        public string GoogleId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
        public object Name { get; internal set; }
    }
}
